apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webcolor-project
  namespace: argocd
spec:
  description: Projeto para aplicação WebColor Exemplo de curso de GitOps
  sourceRepos:
    #- https://github.com/danferreira011/web-page-deploy.git
    #- "!https://github.com/danferreira011/web-page-deploy.git"
    - "https://github.com/danferreira011/*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"      
  clusterResourceWhitelist:
    - kind: "Namespace"
      group: ""
  # namespaceResourceWhitelist:
  #   - kind: Deployment
  #     group: apps
  #   - kind: ReplicaSet
  #     group: apps
  #   - kind: Pod
  #     group: ""
  #   - kind: Service
  #     group: ""
  # namespaceResourceBlacklist:
  #   - kind: "Ingress"
  #     group: "networking.k8s.io"
  # syncWindows:
  # - kind: allow #deny
  #   timeZone: "America/Sao_Paulo"
  #   schedule: '0 9 * * *' #cron format
  #   duration: 2h
  #   manualSync: false #true
  #   applications: 
  #   - "*"
    # namespaces:
    # - "webcolor"
    # clusters:
    # - "https://kubernetes.default.svc"